name: Merge PR, Build and Deploy

on:
  pull_request:

jobs:
  merge-build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4


      - name: Merge pull request into main
        if: github.event.pull_request.merged == false
        uses: peter-evans/merge-pull-request@v4
        with:
          merge-method: squash

      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm ci --prefix backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          package: backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
