name: Merge Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, closed]

jobs:
  merge:
    if: >
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.draft == false &&
      github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Install GH CLI
        run: sudo apt install gh -y

      - name: Authenticate GH CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Merge pull request into main
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --squash --auto
