name: Merge Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Merge pull request into main
        uses: peter-evans/merge-pull-request@v4
        with:
          merge-method: squash